### ISSUE TITLE
Horizontal scroll on narrow screens in Customizer when using a Static Front Page.

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#163] opened 2016-10-06 14:27 UTC
https://cloudup.com/iWgKvz9M5lN

Steps to reproduce:
- Open the theme in the Customizer.
- Set a static front page.
- Narrow screen to 1278px or less.
- Don't scroll down; this only happens when the menu is _not_ stuck to the top.

Using Chrome 53, but it's happening in Firefox as well.

**Comment by ghost** [comment] 2016-10-07 05:35
There were issues with menu scroll down arrow due to transform rotate property - http://take.ms/XylZ9

I have fixed this issue by adding line height: 1 to genericons. By default - for button tag line height 1.5 is applying & its causing issues to increase the width of scroll down arrow.

Now scrollbar is removed - http://take.ms/fFaN5

**Comment by melchoyce** [comment] 2016-10-09 23:51
Would this be fixed by #206?

**Comment by ghost** [comment] 2016-10-12 03:33
@melchoyce Above reported issue can fixed by this PR - https://github.com/WordPress/twentyseventeen/pull/253

Please close this issue as well as PR submitted by me - https://github.com/WordPress/twentyseventeen/pull/179

Thanks for pointing this!

**Comment by samikeijonen** [comment] 2016-10-12 12:52
I can't reproduce this in #253. But I can see horizontal scroll when I have Query Monitor plugin active.

@sixhours can you double check that this is not the case?

**Comment by sixhours** [comment] 2016-10-12 12:54
Nope, I don't have that plugin.

**Comment by samikeijonen** [comment] 2016-10-12 13:09
Did you test it on #253?

**Comment by melchoyce** [comment] 2016-10-12 20:20
I can't reproduce this. Maybe fixed by #206?

**Comment by laurelfulford** [comment] 2016-10-13 02:22
I was able to reproduce this in the master branch. It looks like it's resolved in #253 for me.

**Comment by laurelfulford** [comment] 2016-10-14 21:12
Fixed in #322.

**Closed as completed by laurelfulford** 2016-10-14 21:12 UTC
Labels: bug, has pr
