### ISSUE TITLE
Dropdown menus on touch devices

### ISSUE THREAD

**Issue by trenzterra** [WordPress/twentyseventeen#129] opened 2016-10-02 05:46 UTC
On the older Twenty Sixteen theme, dropdown menus work as intended on large touchscreen devices (such as Windows 10 tablets and touchscreen laptops). You tap on the menu item, and the dropdown menu appears. If you want to open the link on the menu item itself, you wait till the dropdown menu is open before tapping on the menu item again.

Unfortunately, this behaviour has regressed on the Twenty Seventeen theme as of now. Tapping a menu item immediately brings me to the link belonging to the menu item itself. The dropdown menu has no chance of appearing.

You can test this by enabling the responsive design mode + touch emulation mode on both Firefox and Chrome.

**Comment by josephfusco** [comment] 2016-10-02 13:53
Confirmed. Great catch.

**Comment by laurelfulford** [comment] 2016-10-03 03:38
Good find, @trenzterra!

The menu needed to be reworked for #4, so there should be a fix for this in #89. I will leave this open until that PR is merged and the fix can be confirmed.

Thank you!

**Comment by melchoyce** [comment] 2016-10-06 03:23
Is this fixed & good to close?

**Comment by laurelfulford** [comment] 2016-10-10 15:45
Looks like it's now working as expected with #89 merged in.

**Closed as completed by laurelfulford** 2016-10-10 15:45 UTC
Labels: bug
