### ISSUE TITLE
Header color seems says wrong color

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#225] opened 2016-10-09 16:57 UTC
The color says black but it shows white....

![2016-10-09 at 17 55](https://cloud.githubusercontent.com/assets/253067/19222160/c604c7a8-8e49-11e6-84e7-10512c834bde.png)

**Comment by celloexpressions** [comment] 2016-10-09 16:57
Noting that this is unrelated to #116, which doesn't touch the header text color option.

**Comment by davidakennedy** [comment] 2016-10-13 19:52
I'm not sure this can be fixed.

I adjusted it to `#222222` here: https://github.com/WordPress/twentyseventeen/commit/59c59710fd9a97c9a8c0452b3637eaea099ea36e It's that color in most cases.

The issue is that it's #ffffff when it has an image background. We may be able to put the color in a variable and change the default based on whether a header image exists or not. Thoughts @laurelfulford?

**Comment by celloexpressions** [comment] 2016-10-13 20:14
This option should only be available, and apply, when a header image or video is set. We should be able to add an `active_callback` to the control that returns `has_header_image()` for now.

**Comment by celloexpressions** [comment] 2016-10-13 20:17
To further clarify, the header text color should not be individually customizable when it's displayed without an image or video. The only reason the option exists is to ensure that it's visible over an image (and I'm generally not convinced that this option is necessary or the best approach for this).

**Comment by laurelfulford** [comment] 2016-10-14 20:33
@davidakennedy It looks like we can check if a header image is uploaded and change the default colour based on that. Unfortunately to make it work, we'd also need to check whether we're on the front page, which is the only page that displays the header image. I'm not sure this part is actually possible.

I think having it only available and applied when the custom header image/video is visible is a good work around.

**Comment by celloexpressions** [comment] 2016-10-15 17:24
We need this conditional both as an `active_callback` on the header image control (via `get_control( 'header_image' )`) and on outputting CSS for that, that returns:

```
( is_front_page() && has_header_image() )
```

Also, with the new default image, the text color should be black by default, as it provides better contrast on most device sizes depending on the length of the title (basically as long as it doesn't land over the vase). We should consider whether the gradient over the image should be to white instead of black to improve legibility of the title if it's black by default.

**Comment by davidakennedy** [comment] 2016-10-19 03:18
Addressed in #481.

**Closed as completed by davidakennedy** 2016-10-19 03:18 UTC
Labels: bug, pr needed
