### ISSUE TITLE
Pre-formatted text is cut off

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentyseventeen#391] opened 2016-10-16 14:33 UTC
This happens on all devices I tested.

![2016-10-16 at 15 32](https://cloud.githubusercontent.com/assets/253067/19418135/cffb324e-93b5-11e6-8f31-72c9b989583c.png)

**Comment by joyously** [comment] 2016-10-16 15:39
Looks like it needs `pre {overflow:auto}`.

**Comment by melchoyce** [comment] 2016-10-17 03:15
Hey, just took a look and determined this is the expected behavior — the `pre` tag doesn't have line-wraps, so you need to scroll to see more code. 

We could change this by introducing `white-space: pre-wrap;`, but I actually think that introduces a worse code-reading experience. 

Going to close this one, but feel free to re-open if you disagree, or if you find a bug related to this behavior on a touch device.

**Closed as completed by melchoyce** 2016-10-17 03:15 UTC
Labels: bug, pr needed
