### ISSUE TITLE
Footer closing div with no comment

### ISSUE THREAD

**Issue by asathoor** [WordPress/twentyseventeen#63] opened 2016-09-12 08:43 UTC
The /div [https://github.com/WordPress/twentyseventeen/blob/master/footer.php#L14](url)  could have a comment, which div is closed here?

**Comment by LittleBigThing** [comment] 2016-09-12 12:22
`</div><!-- #content -->`

It is opened at the end of header.php

**Comment by asathoor** [comment] 2016-09-13 11:41
thanx, now it's in my forked version.

**Comment by grappler** [comment] 2016-09-13 20:46
Would be good to update the title so that people know that the issue is about at first glance. Something like "Footer closing div without comment"

**Comment by davidakennedy** [comment] 2016-09-28 22:00
Thanks! This was updated here: https://github.com/WordPress/twentyseventeen/commit/7cb718a1282a39b34dfc785fab5bd0e53e949595

**Closed as completed by davidakennedy** 2016-09-28 22:00 UTC
