### ISSUE TITLE
Scroll down function doesn't account for height of fixed menu. 

### ISSUE THREAD

**Issue by tywayne** [WordPress/twentyseventeen#313] opened 2016-10-14 16:01 UTC
When clicking the `.menu-scroll-down` button in menu, it scrolls the content area to top of browser. This results in the title in the content being displayed behind the fixed menu.

![screen shot 2016-10-14 at 10 59 42 am](https://cloud.githubusercontent.com/assets/1395543/19394135/6588d34e-91fd-11e6-889f-3f6cad9f033a.png)

We should offset that scroll to account for the menu and display the title, like so:

![screen shot 2016-10-14 at 10 59 58 am](https://cloud.githubusercontent.com/assets/1395543/19394153/72b70d38-91fd-11e6-8662-9d8a452a4df3.png)

**Comment by melchoyce** [comment] 2016-10-14 16:04
Thanks @tywayne! Looks like this is a duplicate of #280. There's a PR at #274 if you'd like to test it.

**Closed as completed by melchoyce** 2016-10-14 16:04 UTC
