### ISSUE TITLE
A set of two lines at the bottom of single post/page displayed for the logged out users

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#438] opened 2016-10-18 01:46 UTC
There appears to be a set of two parallel lines at the bottom of single post/page content for logged out users.

![image](https://cloud.githubusercontent.com/assets/4550351/19461482/88158ab6-9530-11e6-9dff-5f945dcef4c5.png)

![image](https://cloud.githubusercontent.com/assets/4550351/19461485/90f1d180-9530-11e6-96cc-1ff5cf60de77.png)

This is where the Edit button appears for logged in users.

![image](https://cloud.githubusercontent.com/assets/4550351/19461515/db2493fa-9530-11e6-8f0e-6680b6cce229.png)

**Comment by melchoyce** [comment] 2016-10-18 01:48
Duplicate of #314

**Closed as completed by melchoyce** 2016-10-18 01:48 UTC

**Comment by alaczek** [comment] 2016-10-18 01:50
Sorry! My search powers failed me :|

**Comment by melchoyce** [comment] 2016-10-18 01:52
No worries, we used very different keywords 😅
