### ISSUE TITLE
menu-scroll-down scrolls too far

### ISSUE THREAD

**Issue by joshcummingsdesign** [WordPress/twentyseventeen#280] opened 2016-10-13 06:28 UTC
The menu scroll down scrolls passed the beginning of the content making it hard to read. It's set to the class '#primary', but maybe we can make it so it scrolls to where the bottom of the nav meets the top of the content.

![demo](https://cloud.githubusercontent.com/assets/11913201/19338712/9eddf456-90d3-11e6-96e2-8a3880f05990.gif)

**Comment by joshcummingsdesign** [comment] 2016-10-13 07:25
Proposed fix in #283

**Comment by melchoyce** [comment] 2016-10-13 15:26
Looks like this might be a duplicate of #274?

**Comment by joshcummingsdesign** [comment] 2016-10-13 15:44
duplicate of #274

**Comment by davidakennedy** [comment] 2016-10-13 17:38
Closing this out in favor of earlier PR. Thanks @joshcummingsdesign!

**Closed as completed by davidakennedy** 2016-10-13 17:38 UTC
